name: Build and Publish Container Image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
    paths-ignore:
      - 'compose.yml'
  pull_request:
    branches:
      - main  # Trigger on PR to the main branch
    paths-ignore:
      - 'compose.yml'

jobs:
  build:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    steps:
      - name: Lowercase repository owner
        shell: bash
        run: echo "LOWERCASE_REPO_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Identify Latest Release Tag of Tailscale GitHub Project
        shell: bash
        run: echo "VERSION="$(curl -sX GET "https://api.github.com/repos/tailscale/tailscale/releases/latest" | jq --raw-output '.tag_name' 2>/dev/null)"" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Log in to GitHub Container Registry
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Container image
        run: |
          podman build -t ghcr.io/${{ env.LOWERCASE_REPO_OWNER }}/container-tsidp/tsidp:${{ env.VERSION }} .

      - name: Push Container image with ${{ env.VERSION }} Tag
        run: |
          podman push ghcr.io/${{ env.LOWERCASE_REPO_OWNER }}/container-tsidp/tsidp:${{ env.VERSION }}

      - name: Push Container image with Latest Tag
        run: |
          podman push ghcr.io/${{ env.LOWERCASE_REPO_OWNER }}/container-tsidp/tsidp:latest